
server:
  port: 8251
spring:
  application:
    name: mmall
  datasource: #数据源
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://172.17.0.1:3306/mmall?useUnicode=true&characterEncoding=UTF8&serverTime=Asia/Shanghai
      filters: stat, wall, config
      initial-size: 1
      max-active: 100
      max-wait: 60000
      min-idle: 1
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      validation-query: select 'x'
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      pool-prepared-statements: true
      max-open-prepared-statements: 50
      max-pool-prepared-statement-per-connection-size: 20
      username: root
      password: 123456
      default-transaction-isolation: 2
    name: druidDataSource
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 0
      max-file-size: 100000000
      max-request-size: 100000000
      resolve-lazily: false

#  thymeleaf:
#    prefix: classpath:/templates/
#    suffix: .html

mybatis:
  mapper-locations: classpath:/mappers/*Mapper.xml

#日志配置
#logging:
#  level:
#    root: DEBUG
#    org:
#      springframework: DEBUG
#      mybatis: DEBUG